### ISSUE TITLE
It would be nice if the unit_of_measurement could be natively included

### ISSUE THREAD

**Issue by f616** [sq3tle/prusa_mini_home_assistant#4]
My  workaround was editing the customize.yaml:

```
  sensor.prusa_mini_temp_nozzle:
    friendly_name: "Nozzle Temperature"
    unit_of_measurement: "ºC"
  
  sensor.prusa_mini_temp_bed:
    friendly_name: "Bed Temperature"
    unit_of_measurement: "ºC"

  sensor.prusa_mini_pos_z_mm:
    friendly_name: "Current Z"
    unit_of_measurement: "mm"

  sensor.prusa_mini_progress:
    friendly_name: "Print Progress"
    unit_of_measurement: "%"
```
